# run_pipeline.py
# Master orchestrator.  Run with:  python run_pipeline.py
#
# Execution order for each history window (5y, 10y):
#   Phase 1  fetch raw OHLCV
#   Phase 2  compute 7 dimensionless indicators
#   Phase 3  build Stock2Vec identity vectors (training split only)
#   Phase 4  walk-forward scale + build MIMO datasets
#   Phase 5  train Baseline / OneHot / Stock2Vec models × 2 MIMO modes
#   Phase 6  evaluate on test set
#   Phase 7  experiments E1–E4 + research summary figure
#
# Configure everything in config.py — do not edit this file for normal use.

import os
import random
from copy import deepcopy
from typing import Dict, List

import numpy as np
import torch

from config import CFG

from data.fetcher    import fetch_all, aligned_closes as make_aligned
from data.indicators import compute_all, FEATURE_COLS
from data.scaler     import chronological_split, scale_splits
from data.dataset    import build_datasets

from vectors.stock2vec import build as build_vectors, zero_vector

from models import build_model, SUPPORTED_MODELS
from models.trainer import train

from evaluation.evaluator import run as evaluate
from evaluation.metrics   import improvement_table

from experiments import e1_clustering, e2_ablation, e3_generalization, e4_interpretability
from visualization import plotter


# ── One-hot sector encoding (for ablation model M1) ──────────────
_SECTOR_IDX: Dict[str, int] = {
    "AAPL": 0, "MSFT": 0, "GOOGL": 0, "META": 0,   # Software/Internet
    "IBM":  1,                                        # Enterprise/Legacy
    "NVDA": 2,                                        # Semiconductors
}
_N_SECTORS = 3


def _seed_all(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def _make_onehot(tickers: List[str]) -> Dict[str, np.ndarray]:
    vecs = {}
    for t in tickers:
        v = np.zeros(_N_SECTORS, dtype=np.float32)
        v[_SECTOR_IDX.get(t, 0)] = 1.0
        vecs[t] = v
    return vecs


def _inject(train_ds, val_ds, test_ds, id_vecs: Dict[str, np.ndarray]):
    """Replace identity tensors in all splits in-place."""
    for ds in (train_ds, val_ds, test_ds):
        for s in ds.samples:
            if s["ticker"] in id_vecs:
                s["identity"] = torch.tensor(id_vecs[s["ticker"]],
                                             dtype=torch.float32)


# ─────────────────────────────────────────────────────────────────
def run_window(years: int):
    label  = f"{years}y"
    device = CFG.resolve_device()
    _seed_all(CFG.training.seed)
    CFG.make_dirs()

    print(f"\n{'╔'+'═'*54+'╗'}")
    print(f"  STOCK2VEC  |  {years}-year window  |  device={device}")
    print(f"{'╚'+'═'*54+'╝'}")

    # ── Phase 1: Fetch ────────────────────────────────────────────
    print("\n[Phase 1] Fetching OHLCV …")
    raw = fetch_all(CFG.data.tickers, years, CFG.data.raw_dir)
    tickers = list(raw.keys())

    # ── Phase 2: Indicators ───────────────────────────────────────
    print("\n[Phase 2] Computing indicators …")
    processed = compute_all(raw, CFG.indicators)
    tickers   = [t for t in tickers if t in processed]  # keep successful

    for t, (df_feat, _) in processed.items():
        plotter.indicator_dashboard(df_feat, t,
                                    CFG.experiments.plots_dir, label)

    # ── Phase 3: Stock2Vec (training split only) ──────────────────
    print("\n[Phase 3] Building Stock2Vec vectors …")
    aligned = make_aligned(raw)
    n_tr    = int(len(aligned) * CFG.training.train_ratio)
    identity_vecs, pca_obj, _ = build_vectors(
        aligned.iloc[:n_tr],
        n_components = CFG.vectors.n_components,
        save_dir     = CFG.vectors.vectors_dir,
        label        = label,
    )

    # ── Phase 4: Scale + datasets ─────────────────────────────────
    print("\n[Phase 4] Scaling features …")
    scaled_splits: Dict = {}
    for t in tickers:
        df, cols = processed[t]
        tr, va, te = chronological_split(df, CFG.training.train_ratio,
                                          CFG.training.val_ratio)
        scaled_splits[t] = scale_splits(tr, va, te, cols, CFG.scaler.method)

    ret_idx = FEATURE_COLS.index("close_return")

    # ── Phase 5 & 6: Train + evaluate per MIMO mode ───────────────
    all_results     : Dict = {}   # {mode_label: {model_name: {ticker: metrics}}}
    all_predictions : Dict = {}
    all_histories   : Dict = {}

    for mode, mcfg in CFG.training.modes.items():
        lookback, horizon = mcfg["lookback"], mcfg["horizon"]
        mlbl = f"{label}_{mode}"
        print(f"\n{'─'*54}\n  MODE: {mode.upper()}  lookback={lookback}  "
              f"horizon={horizon}\n{'─'*54}")

        # Build base datasets
        tr_ds, va_ds, te_ds = build_datasets(
            processed, identity_vecs, scaled_splits,
            tickers, lookback, horizon, ret_idx,
        )

        # M0 Baseline  (use_identity=False, no identity vector)
        # M1 OneHot    (use_identity=True,  identity_dim=_N_SECTORS)
        # M2 Stock2Vec (use_identity=True,  identity_dim=n_components)
        variants = {
            "Baseline": (False, zero_vector(CFG.vectors.n_components),
                         CFG.vectors.n_components),
            "OneHot":   (True,  _make_onehot(tickers),
                         _N_SECTORS),
            "Stock2Vec":(True,  identity_vecs,
                         CFG.vectors.n_components),
        }

        mode_res, mode_pred, mode_hist = {}, {}, {}

        for mname, (use_id, id_map, id_dim) in variants.items():
            print(f"\n  ── {mname}  [{mlbl}] ──")

            # Inject the identity this variant was designed for.
            # Baseline : zero vectors (ignored by model, but tensor must exist)
            # OneHot   : 3D one-hot  → effective_input = 7+3 = 10
            # Stock2Vec: 4D PCA      → effective_input = 7+4 = 11
            #
            # BUG FIXED: the old code restored Stock2Vec (4D) before evaluating
            # every variant.  For the OneHot model (expects 10 features) this
            # produced:
            #   RuntimeError: input.size(-1) must be equal to input_size.
            #   Expected 10, got 11
            # Fix: evaluate with the SAME identity that was active during
            # training.  Restore Stock2Vec ONCE after all variants finish.
            if mname == "Baseline":
                zero_map = {t: zero_vector(id_dim) for t in tickers}
                _inject(tr_ds, va_ds, te_ds, zero_map)
            else:
                _inject(tr_ds, va_ds, te_ds, id_map)

            # Build model
            mcopy = deepcopy(CFG.model)
            mcopy.use_identity = use_id
            mcopy.identity_dim = id_dim
            model = build_model(mcopy, len(FEATURE_COLS), horizon)

            ckpt  = os.path.join(CFG.training.models_dir,
                                 f"{mname}_{mlbl}.pt")
            hist  = train(model, tr_ds, va_ds, CFG.training, device, ckpt)

            # Evaluate with the same identity used for training.
            # te_ds already holds the correct tensors — no swap needed here.
            per_stock, agg, preds = evaluate(model, te_ds, device,
                                              CFG.training.batch_size * 2)

            mode_res[mname]  = per_stock
            mode_pred[mname] = preds
            mode_hist[mname] = hist

            # Cumulative return charts (uses already-collected numpy arrays)
            for t, arrays in preds.items():
                plotter.cumulative_return(
                    arrays["y_true"], arrays["y_pred"], arrays["close_refs"],
                    t, mname, CFG.experiments.plots_dir, mlbl,
                )

        # Restore Stock2Vec identity once — needed by leave-one-out below
        _inject(tr_ds, va_ds, te_ds, identity_vecs)

        all_results[mlbl]     = mode_res
        all_predictions[mlbl] = mode_pred
        all_histories[mlbl]   = mode_hist

        # Experiment 2
        e2_ablation.run(
            results               = mode_res,
            predictions_per_model = mode_pred,
            histories             = mode_hist,
            plots_dir             = CFG.experiments.plots_dir,
            results_dir           = CFG.experiments.results_dir,
            label                 = mlbl,
            showcase              = tickers[:3],
        )

    # ── Phase 7: Experiments E1, E3, E4 + summary ─────────────────

    # E1 — clustering
    e1_sum = e1_clustering.run(
        identity_vecs,
        CFG.experiments.plots_dir,
        CFG.experiments.results_dir,
        label,
    )

    # E3 — leave-one-out generalisation
    short_lbl  = f"{label}_short"
    sv_metrics = all_results.get(short_lbl, {}).get("Stock2Vec", {})
    loo        = _leave_one_out(tickers, processed, identity_vecs,
                                scaled_splits, CFG, device, label)
    e3_df = e3_generalization.run(
        loo, identity_vecs, sv_metrics,
        CFG.experiments.plots_dir, CFG.experiments.results_dir, label,
    )

    # E4 — interpretability
    e4_interpretability.run(
        identity_vecs, aligned.iloc[:n_tr],
        CFG.experiments.plots_dir, CFG.experiments.results_dir, label,
    )

    # Research summary
    imp_df = None
    if short_lbl in all_results:
        b = all_results[short_lbl].get("Baseline",  {})
        s = all_results[short_lbl].get("Stock2Vec", {})
        if b and s:
            imp_df = improvement_table(b, s)

    plotter.research_summary(e1_sum, imp_df, e3_df,
                             CFG.experiments.plots_dir, label)

    print(f"\n✅  {years}y window complete.")
    print(f"   plots   → {CFG.experiments.plots_dir}")
    print(f"   results → {CFG.experiments.results_dir}")
    print(f"   models  → {CFG.training.models_dir}")


# ── Leave-one-out helper ──────────────────────────────────────────

def _leave_one_out(tickers, processed, identity_vecs,
                   scaled_splits, cfg, device, label) -> List[Dict]:
    from models import build_model, SUPPORTED_MODELS
    from models.trainer import train as _train
    from evaluation.evaluator import run as _eval
    from data.dataset import build_datasets

    ret_idx = FEATURE_COLS.index("close_return")
    results = []

    for target in tickers:
        train_t = [t for t in tickers if t != target]
        if len(train_t) < 2:
            continue
        print(f"\n  [E3] LOO: held-out = {target}")

        lkb = cfg.training.modes["short"]["lookback"]
        hor = cfg.training.modes["short"]["horizon"]

        tr_ds, va_ds, _ = build_datasets(
            processed, identity_vecs, scaled_splits,
            train_t, lkb, hor, ret_idx,
        )
        _, _, te_ds = build_datasets(
            processed, identity_vecs, scaled_splits,
            [target], lkb, hor, ret_idx,
        )

        mcopy = deepcopy(cfg.model)
        mcopy.use_identity = True
        mcopy.identity_dim = cfg.vectors.n_components
        model = build_model(mcopy, len(FEATURE_COLS), hor)
        _train(model, tr_ds, va_ds, cfg.training, device, checkpoint_path=None)

        per_stock, _, _ = _eval(model, te_ds, device,
                                cfg.training.batch_size * 2)
        if target in per_stock:
            m = per_stock[target]
            results.append({
                "ticker":           target,
                "zero_shot_rmse":   m["rmse_ret"],
                "zero_shot_rawdev": m["raw_dev_mean"],
            })

    return results


# ─────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    for yrs in CFG.data.history_years:
        run_window(yrs)
    print("\n🏁  All windows complete.")
